RDA3/Semana12/GrafosFlask_P2/app.py
from flask import Flask

# Importamos las rutas desde la carpeta routes
from routes import register_blueprints

app = Flask(__name__)

# Registramos los blueprints
register_blueprints(app)

if __name__ == '__main__':
    app.run(debug=True)

RDA3/Semana12/GrafosFlask_P2/routes/__init__.py
from .home_routes import home_bp
from .grafos_routes import starter_bp

def register_blueprints(app):
    app.register_blueprint(home_bp)
    app.register_blueprint(starter_bp)

RDA3/Semana12/GrafosFlask_P2/routes/grafos_routes.py
from flask import Blueprint, render_template, request
from grafo_utils import grafo_a_imagen, camino_optimo_con_costera, obtener_ciudades, grafo_a_imagen, grafo_a_imagen_camino

starter_bp = Blueprint('grafos', __name__, url_prefix='/grafos')

@starter_bp.route('/')
def starter():
    return render_template("grafos/starter.html")

@starter_bp.route('/calcular_camino', methods=['GET', 'POST'])
def calcular_camino():
    ciudades = obtener_ciudades()
    resultado = None
    if request.method == 'POST':
        origen = request.form.get('origen')
        destino = request.form.get('destino')
        if origen and destino and origen != destino:
            resultado = camino_optimo_con_costera(origen, destino)
    return render_template("grafos/calcular_camino.html", ciudades=ciudades, resultado=resultado)

@starter_bp.route('/camino')
def ver_camino():
    resultado = camino_optimo_con_costera("Ibarra", "Loja")
    return render_template("grafos/camino.html", resultado=resultado)

@starter_bp.route('/grafo_imagen')
def grafo_imagen():
    return grafo_a_imagen()

@starter_bp.route('/grafo_imagen_camino')
def grafo_imagen_camino():
    camino = request.args.getlist('camino')
    return grafo_a_imagen_camino(camino)

RDA3/Semana12/GrafosFlask_P2/routes/home_routes.py
from flask import Blueprint, render_template
home_bp = Blueprint('home', __name__)
@home_bp.route('/')
def home():
    return render_template("welcome.html")

RDA3/Semana12/GrafosFlask_P2/templates/base.html
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <title>AdminLTE 3 | Starter</title> -->
  <title>{% block title %}AdminLTE 3 | Starter{% endblock %}</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='adminlte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='adminlte/dist/css/adminlte.min.css') }}">

  <link rel="icon" href="{{ url_for('static', filename='joacobrm/img/favicon.ico') }}" type="image/x-icon">

  <link rel="stylesheet" href="{{ url_for('static', filename='joacobrm/css/estilos.css') }}">

</head>
<body class="hold-transition sidebar-mini">
{% set current_path = request.path %}
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="https://github.com/JoacoBRM" class="brand-link" target="_blank">
      <img src="{{ url_for('static', filename='joacobrm/img/logo_jb.jpeg') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">JoacoBRM</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column">
          <li class="nav-item">
            <a href="{{ url_for('home.home') }}" class="nav-link {% if current_path == url_for('home.home') %}active{% endif %}">
                <i class="nav-icon fas fa-home"></i>
                <p>Inicio</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('grafos.starter') }}" class="nav-link {% if current_path == url_for('grafos.starter') %}active{% endif %}">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>Grafos</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('grafos.calcular_camino') }}" class="nav-link {% if current_path == url_for('grafos.calcular_camino') %}active{% endif %}">
                <i class="nav-icon fas fa-cog"></i>
                <p>Calculo de Rutas</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('grafos.ver_camino') }}" class="nav-link {% if current_path == url_for('grafos.ver_camino') %}active{% endif %}">
                <i class="nav-icon fas fa-chart-line"></i>
                <p>Camino (Ibarra - Loja)</p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <div class="container mt-0">
      <div class="bg-white p-4 rounded shadow">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
    <footer class="main-footer d-flex justify-content-between align-items-center px-3">
    <div>
      <strong>Copyright © 2014-2025 <a href="https://github.com/JoacoBRM">JoacoBRM</a>.</strong>
      All rights reserved.
    </div>
    <div class="text-muted d-none d-sm-inline">
      PUCESA - Programación IV
    </div>
  </footer>

</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ url_for('static', filename='adminlte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ url_for('static', filename='adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='adminlte/dist/js/adminlte.min.js') }}"></script>
</body>
</html>

RDA3/Semana12/GrafosFlask_P2/templates/grafos/calcular_camino.html
{% extends "base.html" %}

{% block title %}Formulario{% endblock %}

{% block content %}

<div class="mb-4">
  <h2 class="mb-4 text-success text-center">Buscar camino más económico</h2>
  <form method="post" class="row g-4 justify-content-center">
    <div class="col-12 col-md-4 d-flex flex-column align-items-center">
      <label for="origen" class="titulo-ciudad text-center">🌍 Ciudad de origen</label>
      <select name="origen" id="origen" class="form-select form-select-lg form-select-custom mb-3" required>
        {% for ciudad in ciudades %}
          <option value="{{ ciudad }}"
            {% if request.form.origen == ciudad %}selected{% endif %}>
            {{ ciudad }}
          </option>
        {% endfor %}
      </select>
    </div>

    <div class="col-12 col-md-4 d-flex flex-column align-items-center">
      <label for="destino" class="titulo-ciudad text-center">📍 Ciudad de destino</label>
      <select name="destino" id="destino" class="form-select form-select-lg form-select-custom mb-3" required>
        {% for ciudad in ciudades %}
          <option value="{{ ciudad }}"
            {% if request.form.destino == ciudad %}selected{% endif %}>
            {{ ciudad }}
          </option>
        {% endfor %}
      </select>
    </div>

    <div class="col-12 text-center">
      <button type="submit" class="btn btn-success btn-lg px-5 mt-3 shadow-sm">Calcular</button>
    </div>
  </form>
</div>


{% if resultado %}
    <h3>Resultado</h3>
    <p><strong>Ruta:</strong> {{ resultado.camino | join(" → ") }}</p>
    <p><strong>Costo total:</strong> ${{ resultado.costo }}</p>
    {% if resultado.valido %}
        <p style="color: green;"><strong>✅ El camino incluye una ciudad costera.</strong></p>
    {% else %}
        <p style="color: red;"><strong>❌ El camino NO pasa por ciudad costera.</strong></p>
    {% endif %}
    {% if resultado.camino %}
        <div class="text-center">
            <img src="{{ url_for('grafos.grafo_imagen_camino', **{'camino': resultado.camino}) }}"
                 alt="Grafo con camino resaltado"
                 class="img-fluid"
                 style="width:450px; height:auto; margin-top: 5px;"/>
        </div>
    {% else %}
        <div class="text-center">
            <img src="{{ url_for('grafos.grafo_imagen') }}"
                 alt="Grafo de ciudades"
                 class="img-fluid"
                 style="width:450px; height:auto; margin-top: 5px;"/>
        </div>
    {% endif %}
{% else %}
    <div class="text-center">
        <img src="{{ url_for('grafos.grafo_imagen') }}"
             alt="Grafo de ciudades"
             class="img-fluid"
             style="width:570px; height:auto; margin-top: 5px;"/>
    </div>
{% endif %}

<p><a href="{{ url_for('grafos.ver_camino') }}">Ruta fija Ibarra → Loja</a></p>


{% endblock %}

RDA3/Semana12/GrafosFlask_P2/templates/grafos/camino.html
{% extends 'base.html' %}

{% block title %}Calcular Camino Óptimo{% endblock %}

{% block content %}
<div class="container mt-4">
     <h2 class="mb-4 text-success text-center">Resultado del camino óptimo: Ibarra → Loja</h2>

    {% if resultado.camino %}
        <p><strong>Ruta:</strong> {{ resultado.camino | join(" → ") }}</p>
        <p><strong>Costo total:</strong> ${{ resultado.costo }}</p>
        {% if resultado.valido %}
            <p style="color: green;"><strong>✅ El camino incluye una ciudad costera.</strong></p>
        {% else %}
            <p style="color: red;"><strong>❌ El camino NO pasa por ciudad costera.</strong></p>
        {% endif %}
    {% else %}
        <p><strong>No se encontró un camino entre Ibarra y Loja.</strong></p>
    {% endif %}
    <div class="text-center">
        <img src="{{ url_for('grafos.grafo_imagen') }}" alt="Grafo de ciudades" class="img-fluid" style="width:700px; height:auto; margin-top: 5px;" />
    </div>
</div>
{% endblock %}

RDA3/Semana12/GrafosFlask_P2/templates/grafos/starter.html
{% extends "base.html" %}
{% block title %}Introducción a los Grafos{% endblock %}

{% block content %}
                <div class="card-header bg-primary text-white">
                    <h2><i class="fas fa-project-diagram"></i> Introducción a los Grafos</h2>
                </div>
                <div class="card-body">
                    <p class="lead">
                        Un <strong>grafo</strong> es una estructura matemática utilizada para modelar relaciones entre objetos. 
                        Está compuesto por <b>nodos</b> (o vértices) y <b>aristas</b> (o enlaces) que conectan pares de nodos.
                    </p>
                    <hr>
                    <div class="row">
                        <div class="col-md-6">
                            <h4><i class="fas fa-circle"></i> Componentes principales</h4>
                            <ul>
                                <li><b>Nodo (Vértice):</b> Representa un objeto o entidad.</li>
                                <li><b>Arista (Enlace):</b> Representa la relación o conexión entre dos nodos.</li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <h4><i class="fas fa-random"></i> Tipos de grafos</h4>
                            <ul>
                                <li><b>Dirigido:</b> Las aristas tienen dirección (como una flecha).</li>
                                <li><b>No dirigido:</b> Las aristas no tienen dirección.</li>
                                <li><b>Ponderado:</b> Las aristas tienen un valor o peso asociado.</li>
                            </ul>
                        </div>
                    </div>
                    <hr>
                    <h5><i class="fas fa-lightbulb"></i> ¿Dónde se usan los grafos?</h5>
                    <ul>
                        <li>Redes sociales</li>
                        <li>Mapas y rutas</li>
                        <li>Internet y redes de computadoras</li>
                        <li>Biología y química</li>
                        <li>Muchos otros campos</li>
                    </ul>
                    <div class="text-center mt-4">
                        <i class="fas fa-network-wired fa-4x text-primary"></i>
                        <p class="mt-3">¡Explora el fascinante mundo de los grafos en este proyecto!</p>
                    </div>
                </div>
{% endblock %}

RDA3/Semana12/GrafosFlask_P2/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='/joacobrm/css/estilos.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='joacobrm/img/favicon.ico') }}" type="image/x-icon">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    
    <title>Práctica</title>
</head>
<body class="main_body">
    <nav class="navbar navbar-expand navbar-dark bg-primary w-100" style="background: linear-gradient(90deg, #fe310d 0%, #a2ff00 100%);">
        <div class="container-fluid">
            <!-- ...existing code... -->
            <span id="user-mention" style="color:rgb(255, 255, 255); cursor:pointer;">@joacobrm</span>

            <div id="user-popup" style="display:none; position:absolute; background:#fff; border:1px solid #ccc; padding:10px; z-index:100; color:white; background:#000000;">
                <strong>JoacoBRM</strong><br>
                <img src="{{ url_for('static', filename='/joacobrm/img/logo_jb.jpeg')}}" alt="JoacoBRM" class="img-fluid" style="width:100px; height:auto; margin-top: 5px; "><br>
                Nombre: Joaquín Bermeo<br>
                Email: jbrm2601@gmail.com<br>
                Desarrollador full stack.<br>
                Mi GitHub: <a href="https://github.com/JoacoBRM" target="_blank">Github</a>
            </div>
        </div>
    </nav>

    <main class="contenedor flex-grow-1 d-flex flex-column justify-content-center align-items-center">
        <img src="{{ url_for('static', filename='/joacobrm/img/grafo_main.png')}}" class="img-main" alt="Ejemplo Grafo">
        <h1 class="welcome_h1">Grafos con Flask</h1> 
        <button id="btn-abrir" class="glow-on-hover">Haz clic aquí</button>
    </main>

    <footer>Realizado por: Joaquín Bermeo</footer>
    <script src="{{ url_for('static', filename='/joacobrm/js/scripts.js') }}"></script>
</body>
</html>